// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKmPEEG9u4nZ83C1-VqtcDwCCdyugFrMg',
    appId: '1:485408262601:web:594ccdd11dd9ca0a5b4018',
    messagingSenderId: '485408262601',
    projectId: 'webapp-c8a3f',
    authDomain: 'webapp-c8a3f.firebaseapp.com',
    storageBucket: 'webapp-c8a3f.firebasestorage.app',
    measurementId: 'G-1RL31KBSGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Ao3jA5bz0HHdxIC2z866DTEYSs9crcs',
    appId: '1:485408262601:android:e49b7e6efd6345945b4018',
    messagingSenderId: '485408262601',
    projectId: 'webapp-c8a3f',
    storageBucket: 'webapp-c8a3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj2gWbpnD1eYrQZjx-okrW1XZcYwj-UtE',
    appId: '1:485408262601:ios:e2ece04b69762f3b5b4018',
    messagingSenderId: '485408262601',
    projectId: 'webapp-c8a3f',
    storageBucket: 'webapp-c8a3f.firebasestorage.app',
    iosBundleId: 'com.example.webapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj2gWbpnD1eYrQZjx-okrW1XZcYwj-UtE',
    appId: '1:485408262601:ios:e2ece04b69762f3b5b4018',
    messagingSenderId: '485408262601',
    projectId: 'webapp-c8a3f',
    storageBucket: 'webapp-c8a3f.firebasestorage.app',
    iosBundleId: 'com.example.webapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKmPEEG9u4nZ83C1-VqtcDwCCdyugFrMg',
    appId: '1:485408262601:web:cda788f58eb7c2115b4018',
    messagingSenderId: '485408262601',
    projectId: 'webapp-c8a3f',
    authDomain: 'webapp-c8a3f.firebaseapp.com',
    storageBucket: 'webapp-c8a3f.firebasestorage.app',
    measurementId: 'G-PN714LRT1T',
  );
}
