name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main  # Change to your default branch if not 'main'

# jobs:
#   build-and-deploy:
#     name: Build and Deploy
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout the code
#       - name: Checkout repository
#         uses: actions/checkout@v3

#       # Step 2: Set up Flutter
#       - name: Set up Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.24.4'  # Use the specific version of Flutter if needed

#       # Install the dart
#       - name: Install Dart
#         run: flutter upgrade

#       # Step 3: Install dependencies
#       - name: Install dependencies
#         run: flutter pub get

#       # Step 4: Build the Flutter web app
#       - name: Build web
#         run: flutter build web --release

#       # Step 5: Deploy to Firebase Hosting
#       - name: Deploy to Firebase Hosting
#         uses: w9jds/firebase-action@v2.2.0
#         with:
#           args: deploy --only hosting
#         env:
#           FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.3'
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ninja-build libgtk-3-dev
    - name: Install Android SDK
      run: |
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip -O android-sdk.zip
        unzip android-sdk.zip -d android-sdk
        yes | android-sdk/tools/bin/sdkmanager --licenses
        android-sdk/tools/bin/sdkmanager "platform-tools" "platforms;android-30"
    - name: Build web
      run: flutter build web --release
    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@v2.2.0
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}